trigger:
- main

pool:
  vmImage: 'macos-latest'
  name: 'Default'

variables:
  MAVEN_HOME: '/opt/homebrew'
  PATH: '/opt/homebrew/bin:$(PATH)'

stages:
- stage: GetSourceCode
  jobs:
  - job: Checkout
    steps:
    - checkout: self
      persistCredentials: true
      clean: true
      fetchDepth: 0
    - bash: echo 'Demo Test'
      displayName: 'Echo Demo Test'

- stage: BuildCode
  jobs:
  - job: Build
    steps:
    - bash: |
        bash --version  # Check bash version to verify it's available
        mvn compile
      displayName: 'Compile Code'

- stage: RunTests
  jobs:
  - job: Test
    steps:
    - bash: |
        mvn clean test
      displayName: 'Run Tests'
